# Generated by Django 2.1.5 on 2019-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
