# Generated by Django 2.1.5 on 2019-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20190624_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstore',
            name='additives',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='additives_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='additives_tags',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='alcohol_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='allergens',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='allergens_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='alphalinolenicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='arachidicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='arachidonicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='behenicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='betacarotene_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='bicarbonate_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='biotin_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='brands',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='brands_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='butyricacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='caffeine_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='calcium_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='capricacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='caproicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='caprylicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='carbohydrates_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='carbonfootprint_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='casein_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='categories',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='categories_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='categories_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ceroticacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='chloride_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='chlorophyl_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='cholesterol_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='chromium_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='cities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='cities_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='cocoa_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='collagenmeatproteinratio_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='copper_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='countries',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='countries_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='countries_tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='created_datetime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='created_t',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='dihomogammalinolenicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='docosahexaenoicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='eicosapentaenoicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='elaidicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='emb_codes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='emb_codes_tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='energy_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='energyfromfat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='erucicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='fat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='fiber_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='first_packaging_code_geo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='fluoride_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='folates_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='fructose_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='fruitsvegetablesnuts_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='fruitsvegetablesnutsestimate_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='gammalinolenicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='generic_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='glucose_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='glycemicindex_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='gondoicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='image_small_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_from_palm_oil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_from_palm_oil_n',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_from_palm_oil_tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_that_may_be_from_palm_oil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ingredients_that_may_be_from_palm_oil_tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='iodine_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='iron_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='labels',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='labels_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='labels_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='lactose_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='last_modified_datetime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='last_modified_t',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='lauricacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='lignocericacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='linoleicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='magnesium_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='main_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='main_category_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='maltodextrins_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='maltose_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='manganese_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='manufacturing_places',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='manufacturing_places_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='meadacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='melissicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='molybdenum_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='monounsaturatedfat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='montanicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='myristicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='nervonicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='no_nutriments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='nucleotides_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='nutrition_grade_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='nutrition_grade_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='nutritionscorefr_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='nutritionscoreuk_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='oleicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='omega3fat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='omega6fat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='omega9fat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='origins',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='origins_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='packaging',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='packaging_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='palmiticacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='pantothenicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='ph_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='phosphorus_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='pnns_groups_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='pnns_groups_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='polyols_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='polyunsaturatedfat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='potassium_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='proteins_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='purchase_places',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='salt_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='saturatedfat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='selenium_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='serumproteins_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='serving_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='silica_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='sodium_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='starch_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='states',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='states_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='states_tags',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='stearicacid_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='stores',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='sucrose_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='sugars_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='taurine_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='traces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='traces_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='traces_tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='transfat_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitamina_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminb12_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminb1_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminb2_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminb6_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminb9_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminc_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitamind_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitamine_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitamink_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='vitaminpp_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='waterhardness_100g',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodstore',
            name='zinc_100g',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
