# Generated by Django 2.1.5 on 2019-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20190624_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstore',
            name='product_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
